sonar.projectKey=ArulChinnappa12112004_python-CI-CD
sonar.organization=arulchinnappa12112004

sonar.sources=.
sonar.sourceEncoding=UTF-8

sonar.python.version=3.11

sonar.exclusions=**/__pycache__/**,**/venv/**,**/.venv/**